on:
  pull_request:
    branches: [ main ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectKey: "fga-eps-mds_2023-1-MeasureSoftGram-Front"
          msgramConfigPath: "./.github/input/msgram.json"