name: Unit Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
        env:
          SQHost: ${{ secrets.SQHost }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
